### ISSUE TITLE
Cant install easy-thumbnails with Poetry and Django 4

### ISSUE THREAD

**Issue by adrenaline681** [SmileyChris/easy-thumbnails#592]
When I try to install easy-thumbnails using Poetry with Django 4 I get the following error:

` Because no versions of easy-thumbnails match >2.8,<3.0
   and easy-thumbnails (2.8) depends on django (>=2.2,<4.0), easy-thumbnails (>=2.8,<3.0) requires django (>=2.2,<4.0).
  So, because activifinder-api depends on both Django (^4.0.1) and easy-thumbnails (^2.8), version solving failed.
`

**Comment by brylie** [comment]
I added the following to my `pyproject.toml`

```toml
easy-thumbnails = { git = "git@github.com:SmileyChris/easy-thumbnails.git" }
```

However, now I get a long time-out when running `poetry update`. It doesn't seem to resolve the dependency graph.

**Comment by brylie** [comment]
Update: try adding the following to your `pyproject.toml` and then running `poetry update`

```toml
[tool.poetry.dependencies]
easy-thumbnails = { git = "https://github.com/SmileyChris/easy-thumbnails.git" }
```
